### ISSUE TITLE
Can't build code to exe due to error

### ISSUE THREAD

**Issue by damare01** [Frost-06/water-billing-management-system#3]
![Screenshot (282)](https://user-images.githubusercontent.com/81298872/172054281-f897bbf4-2076-4c25-8c86-c96bb6b61f94.png)
![Screenshot (283)](https://user-images.githubusercontent.com/81298872/172054284-3cc4ee97-9ced-4636-a9d7-5a1cc5b4bfa1.png)

**Comment by Gerv-G** [comment]
The project has a reference to a DLL that is perhaps only available to the author's local machine.
See the highlighted lines in [Aquatric2.csproj](https://github.com/Frost-06/water-billing-management-system/blob/d4089bef7cfb5638f1e4675d80ceac4f6be0c75a/Aquatric2/Aquatric2.csproj#L51-L56)

These assemblies should be included in the solution as well.

**Comment by Frost-06** [comment]
You need to purchase a [guna framework](https://gunaui.com/pricing/) for UI WinForms. It is used for a modern look type of tools for WinForms
